### ISSUE TITLE
Is it possible to make project available in Ansible Galaxy

### ISSUE THREAD

**Issue by andreyrusanov** [CSC-IT-Center-for-Science/ansible-role-disk-scheduler#3]
I believe it would be nice to officially publish project in Ansible Galaxy(as I can see it isn't there) - it is more convenient than install it from GitHub. 

Is it looks like good idea and there is anything I can help with - I'm ready to participate,

**Comment by martbhell** [comment]
Good idea!

I clicked on some things in galaxy this should be doable now:

<pre>ansible-galaxy install CSC-IT-Center-for-Science.disk-scheduler 
</pre>

**Comment by martbhell** [comment]
As for things to add - it would be cool to do some testing of this role. I usually use travis, but haven't played with block devices in either LXC or Docker containers.
